FROM node:22.13.0

RUN apt update && \
    apt install -y git-all




COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

WORKDIR /app

RUN npm install

ENTRYPOINT ["npm","run","dev"]

