version: '3'

services:
  docs:
    image: zlattice:docs
    volumes:
      - ./docs:/app/docs
      - ./:/app
    network_mode: host
  sync:
    image: sync:docs
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: host
