version: '3'

services:
  docs:
    image: zlattice:docs
    volumes:
      - ./node_modules:/app/node_modules
      - ./docs:/app/docs
    network_mode: "host"
    working_dir: /app
    command: "npm run docs:dev"

