/**
 * @fileoverview gRPC-Web generated client stub for knowledge_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.1
// source: knowledge_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as knowledge_service_pb from './knowledge_service_pb'; // proto import: "knowledge_service.proto"


export class KnowledgeServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorChat = new grpcWeb.MethodDescriptor(
    '/knowledge_service.KnowledgeService/Chat',
    grpcWeb.MethodType.UNARY,
    knowledge_service_pb.ChatRequest,
    knowledge_service_pb.ChatResponse,
    (request: knowledge_service_pb.ChatRequest) => {
      return request.serializeBinary();
    },
    knowledge_service_pb.ChatResponse.deserializeBinary
  );

  chat(
    request: knowledge_service_pb.ChatRequest,
    metadata?: grpcWeb.Metadata | null): Promise<knowledge_service_pb.ChatResponse>;

  chat(
    request: knowledge_service_pb.ChatRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.ChatResponse) => void): grpcWeb.ClientReadableStream<knowledge_service_pb.ChatResponse>;

  chat(
    request: knowledge_service_pb.ChatRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.ChatResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/knowledge_service.KnowledgeService/Chat',
        request,
        metadata || {},
        this.methodDescriptorChat,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/knowledge_service.KnowledgeService/Chat',
    request,
    metadata || {},
    this.methodDescriptorChat);
  }

  methodDescriptorSubmitFeedback = new grpcWeb.MethodDescriptor(
    '/knowledge_service.KnowledgeService/SubmitFeedback',
    grpcWeb.MethodType.UNARY,
    knowledge_service_pb.FeedbackRequest,
    knowledge_service_pb.FeedbackResponse,
    (request: knowledge_service_pb.FeedbackRequest) => {
      return request.serializeBinary();
    },
    knowledge_service_pb.FeedbackResponse.deserializeBinary
  );

  submitFeedback(
    request: knowledge_service_pb.FeedbackRequest,
    metadata?: grpcWeb.Metadata | null): Promise<knowledge_service_pb.FeedbackResponse>;

  submitFeedback(
    request: knowledge_service_pb.FeedbackRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.FeedbackResponse) => void): grpcWeb.ClientReadableStream<knowledge_service_pb.FeedbackResponse>;

  submitFeedback(
    request: knowledge_service_pb.FeedbackRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.FeedbackResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/knowledge_service.KnowledgeService/SubmitFeedback',
        request,
        metadata || {},
        this.methodDescriptorSubmitFeedback,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/knowledge_service.KnowledgeService/SubmitFeedback',
    request,
    metadata || {},
    this.methodDescriptorSubmitFeedback);
  }

  methodDescriptorGetFeedbackHistory = new grpcWeb.MethodDescriptor(
    '/knowledge_service.KnowledgeService/GetFeedbackHistory',
    grpcWeb.MethodType.UNARY,
    knowledge_service_pb.FeedbackHistoryRequest,
    knowledge_service_pb.FeedbackHistoryResponse,
    (request: knowledge_service_pb.FeedbackHistoryRequest) => {
      return request.serializeBinary();
    },
    knowledge_service_pb.FeedbackHistoryResponse.deserializeBinary
  );

  getFeedbackHistory(
    request: knowledge_service_pb.FeedbackHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<knowledge_service_pb.FeedbackHistoryResponse>;

  getFeedbackHistory(
    request: knowledge_service_pb.FeedbackHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.FeedbackHistoryResponse) => void): grpcWeb.ClientReadableStream<knowledge_service_pb.FeedbackHistoryResponse>;

  getFeedbackHistory(
    request: knowledge_service_pb.FeedbackHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.FeedbackHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/knowledge_service.KnowledgeService/GetFeedbackHistory',
        request,
        metadata || {},
        this.methodDescriptorGetFeedbackHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/knowledge_service.KnowledgeService/GetFeedbackHistory',
    request,
    metadata || {},
    this.methodDescriptorGetFeedbackHistory);
  }

  methodDescriptorGetStats = new grpcWeb.MethodDescriptor(
    '/knowledge_service.KnowledgeService/GetStats',
    grpcWeb.MethodType.UNARY,
    knowledge_service_pb.StatsRequest,
    knowledge_service_pb.StatsResponse,
    (request: knowledge_service_pb.StatsRequest) => {
      return request.serializeBinary();
    },
    knowledge_service_pb.StatsResponse.deserializeBinary
  );

  getStats(
    request: knowledge_service_pb.StatsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<knowledge_service_pb.StatsResponse>;

  getStats(
    request: knowledge_service_pb.StatsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.StatsResponse) => void): grpcWeb.ClientReadableStream<knowledge_service_pb.StatsResponse>;

  getStats(
    request: knowledge_service_pb.StatsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.StatsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/knowledge_service.KnowledgeService/GetStats',
        request,
        metadata || {},
        this.methodDescriptorGetStats,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/knowledge_service.KnowledgeService/GetStats',
    request,
    metadata || {},
    this.methodDescriptorGetStats);
  }

  methodDescriptorSearchDocuments = new grpcWeb.MethodDescriptor(
    '/knowledge_service.KnowledgeService/SearchDocuments',
    grpcWeb.MethodType.UNARY,
    knowledge_service_pb.SearchRequest,
    knowledge_service_pb.SearchResponse,
    (request: knowledge_service_pb.SearchRequest) => {
      return request.serializeBinary();
    },
    knowledge_service_pb.SearchResponse.deserializeBinary
  );

  searchDocuments(
    request: knowledge_service_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<knowledge_service_pb.SearchResponse>;

  searchDocuments(
    request: knowledge_service_pb.SearchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.SearchResponse) => void): grpcWeb.ClientReadableStream<knowledge_service_pb.SearchResponse>;

  searchDocuments(
    request: knowledge_service_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.SearchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/knowledge_service.KnowledgeService/SearchDocuments',
        request,
        metadata || {},
        this.methodDescriptorSearchDocuments,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/knowledge_service.KnowledgeService/SearchDocuments',
    request,
    metadata || {},
    this.methodDescriptorSearchDocuments);
  }

  methodDescriptorHealthCheck = new grpcWeb.MethodDescriptor(
    '/knowledge_service.KnowledgeService/HealthCheck',
    grpcWeb.MethodType.UNARY,
    knowledge_service_pb.HealthCheckRequest,
    knowledge_service_pb.HealthCheckResponse,
    (request: knowledge_service_pb.HealthCheckRequest) => {
      return request.serializeBinary();
    },
    knowledge_service_pb.HealthCheckResponse.deserializeBinary
  );

  healthCheck(
    request: knowledge_service_pb.HealthCheckRequest,
    metadata?: grpcWeb.Metadata | null): Promise<knowledge_service_pb.HealthCheckResponse>;

  healthCheck(
    request: knowledge_service_pb.HealthCheckRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.HealthCheckResponse) => void): grpcWeb.ClientReadableStream<knowledge_service_pb.HealthCheckResponse>;

  healthCheck(
    request: knowledge_service_pb.HealthCheckRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: knowledge_service_pb.HealthCheckResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/knowledge_service.KnowledgeService/HealthCheck',
        request,
        metadata || {},
        this.methodDescriptorHealthCheck,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/knowledge_service.KnowledgeService/HealthCheck',
    request,
    metadata || {},
    this.methodDescriptorHealthCheck);
  }

}

