name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    outputs:
      image-path: ${{ steps.save-image.outputs.image-path }}  # 输出保存的镜像路径，供 deploy 使用

    steps:
      - uses: actions/checkout@v4  # 检出代码

      # Step 1: 设置 Docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 2: 构建 Docker 镜像
      - name: Build Docker image
        id: build-image
        run: |
          IMAGE_TAG=latticeBCLab/zlatticeDocs:latest
          docker build . --file Dockerfile_github --tag $IMAGE_TAG

      # Step 3: 保存镜像为 tar 文件
      - name: Save Docker image to tar
        id: save-image
        run: |
          IMAGE_TAG=latticeBCLab/zlatticeDocs:latest
          IMAGE_PATH="zlatticeDocs_latest.tar"
          docker save -o $IMAGE_PATH $IMAGE_TAG
          echo "image-path=$IMAGE_PATH" >> $GITHUB_OUTPUT
        outputs:
          image-path: ${{ steps.save-image.outputs.image-path }}  # 输出保存的镜像路径

  deploy:
    runs-on: ubuntu-22.04
    needs: build  # 确保在 build 完成后再进行 deploy

    steps:
      - uses: actions/checkout@v4  # 检出代码

      # Step 1: 加载镜像
      - name: Load Docker image
        run: |
          IMAGE_PATH="${{ needs.build.outputs.image-path }}"
          docker load -i $IMAGE_PATH

      # Step 2: 设置 Docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: 使用 docker-compose 启动容器
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.github.yml up -d
